// Single source of truth for headline numbers shown in the app.
// Dynamic numbers (PORTFOLIO, MAPE, FORECAST_2024, DRIVERS, STRESS_2030, HEADLINE)
// are imported from `key_numbers_python.json`, which is regenerated by
// `analysis/python/analysis.ipynb` and copied here by the `sync-data` npm script
// (runs automatically as `predev` / `prebuild`).
//
// External / static reference data (EM-DAT detail, ND-GAIN full table, market
// structure citations, recommendations) stays hand-typed below — these are
// commentary anchors not produced by the modelling pipeline.

import canon from './key_numbers_python.json';

const KIND_OF: Record<string, 'scale' | 'tech' | 'land'> = {
  log_GDP: 'scale',
  log_pop: 'scale',
  urban_pop_pct: 'scale',
  GDP_per_capita_2015USD: 'scale',
  CO2_intensity_GDP: 'tech',
  industry_pct_GDP: 'tech',
  renewable_energy_pct: 'tech',
  forest_area_pct: 'land',
  agri_land_pct: 'land',
};

const PRETTY: Record<string, string> = {
  log_GDP: 'GDP (log)',
  log_pop: 'Population (log)',
  urban_pop_pct: 'Urban pop %',
  GDP_per_capita_2015USD: 'GDP / capita',
  CO2_intensity_GDP: 'CO₂ intensity / GDP',
  industry_pct_GDP: 'Industry % GDP',
  renewable_energy_pct: 'Renewable energy %',
  forest_area_pct: 'Forest area %',
  agri_land_pct: 'Agriculture land %',
};

// === Dynamic exports — sourced from key_numbers_python.json ===

export const PORTFOLIO = {
  gwpUsdM: canon.headline.gwp_usdm,
  baseLossRatio: canon.headline.base_lr,
  elasticity: canon.headline.elasticity,
};

export const MAPE = {
  log_linear: canon.mape_summary.log_linear,
  ARIMA: canon.mape_summary.ARIMA,
  XGBoost: canon.mape_summary.XGBoost_M3a,
  XGBoost_M3b: canon.mape_summary.XGBoost_M3b,
};

export const FORECAST_2024 = [...canon.m3a_per_country]
  .sort((a, b) => b.actual_2024 - a.actual_2024)
  .map((r) => ({
    country: r.country,
    pred: r.pred_2024,
    actual: r.actual_2024,
    errPct: r.err_pct,
  }));

export const DRIVERS = Object.entries(canon.feature_importance_m3b)
  .map(([feature, gain]) => ({
    feature: PRETTY[feature] ?? feature,
    gain: gain as number,
    kind: KIND_OF[feature] ?? 'tech',
  }))
  .sort((a, b) => b.gain - a.gain);

const SCENARIO_FAMILY: Record<string, string> = {
  'Net Zero 2050':         'Orderly',
  'Mitigation (proposed)': 'Client-specific',
  'Delayed Transition':    'Disorderly',
  'Current Policies':      'Hot House World',
};
const SCENARIO_GROWTH: Record<string, number> = {
  'Net Zero 2050':         -0.025,
  'Mitigation (proposed)': -0.010,
  'Delayed Transition':     0.010,
  'Current Policies':       0.025,
};

export const STRESS_2030 = canon.stress_test_2030_aggregate
  .map((s) => ({
    scenario: s.scenario === 'Mitigation (proposed)' ? 'Mitigation' : s.scenario,
    family: SCENARIO_FAMILY[s.scenario] ?? '',
    growth: SCENARIO_GROWTH[s.scenario] ?? 0,
    emissionsMt: Math.round(s.emissions),
    lr: s.lr,
    lossUsdM: Math.round(s.expected_loss_USDm),
  }))
  .sort((a, b) => a.lossUsdM - b.lossUsdM);

export const HEADLINE = {
  lossSwingUsdM: Math.round(canon.headline.loss_swing_usdm),
  lrSwingPp: Math.round(canon.headline.lr_swing_pp),
  mapeXGBPct: canon.mape_summary.XGBoost_M3a,
  vnVsPhGhgGrowthMultiple: 5,
};

// === Static / external reference data — hand-typed ===

// EM-DAT Country Profiles (HDX snapshot 2026-04-24), 2018–2023, ISO3 = VNM/PHL.
// JSON has aggregate EM-DAT in vn_vs_ph; we keep storms/floods/other detail here.
export const EMDAT_VN_PH = {
  vietnam: {
    events: 48,
    perYear: 8.0,
    storms: 26,
    floods: 21,
    other: 1,
    affectedM: 4.5,
    deaths: 620,
    damageUsdBn2024: 2.30,
  },
  philippines: {
    events: 75,
    perYear: 12.5,
    storms: 41,
    floods: 13,
    other: 21, // earthquakes + volcanic + mass movement + drought
    affectedM: 54.5,
    deaths: 2008,
    damageUsdBn2024: 4.81,
  },
  insuredShareSigma: 0.12, // Swiss Re sigma 1/2024 SEA benchmark
};

// Insurance market structure for the VN vs PH comparison.
// Sources: Swiss Re sigma 1/2024 (penetration, protection gap); Vietnam Briefing
// 2024-12 (VN non-life +10.2 % YoY); PH Insurance Commission Q3 2024 stats.
export const MARKET_STRUCTURE = {
  vietnam:     { penetrationPct: 2.4, protectionGapPct: 92, nonLifeYoYPct: 10.2 },
  philippines: { penetrationPct: 1.7, protectionGapPct: 85, nonLifeYoYPct: 10.2 },
};

// Sector-weighted loss-ratio sensitivity for a Power-heavy book in each country
// (Hot House → Net Zero swing). Derived in deliverables/04_vn_vs_ph §7.
export const LR_SENSITIVITY_PP = { vietnam: 13.0, philippines: 2.0 };

// 2024 live data point — Hannover Re Annual Report 2024 statement on Yagi.
export const YAGI_2024 = {
  economicLossUsdBn: 14.0,   // Munich Re region-wide
  insuredLossUsdBn:  1.0,    // Munich Re region-wide
  vnInsuredUsdM:    471,     // VND 11.6 trn local insurer aggregate
  hannoverNote: 'Hannover Re 2024 AR: "Despite Typhoon Yagi, losses incurred… in Vietnam came in within our expectations."',
};

// ND-GAIN Country Index 2026 release, 2023 latest values
export const NDGAIN_2023 = [
  { country: 'Singapore',         iso3: 'SGP', gain: 70.6, vuln: 0.389, ready: 0.800 },
  { country: 'Malaysia',          iso3: 'MYS', gain: 56.9, vuln: 0.367, ready: 0.506 },
  { country: 'Brunei Darussalam', iso3: 'BRN', gain: 56.7, vuln: 0.404, ready: 0.538 },
  { country: 'Thailand',          iso3: 'THA', gain: 52.7, vuln: 0.435, ready: 0.489 },
  { country: 'Indonesia',         iso3: 'IDN', gain: 48.4, vuln: 0.430, ready: 0.398 },
  { country: 'Vietnam',           iso3: 'VNM', gain: 48.1, vuln: 0.468, ready: 0.429 },
  { country: 'Philippines',       iso3: 'PHL', gain: 45.6, vuln: 0.444, ready: 0.356 },
  { country: 'Lao PDR',           iso3: 'LAO', gain: 42.5, vuln: 0.486, ready: 0.336 },
  { country: 'Cambodia',          iso3: 'KHM', gain: 40.5, vuln: 0.481, ready: 0.292 },
  { country: 'Myanmar',           iso3: 'MMR', gain: 36.9, vuln: 0.514, ready: 0.252 },
];

export type Recommendation = {
  id: string;
  ticker: string;
  title: string;
  detail: string;
  target: string;
  owner: string;
  milestone: string;
  policyId: string;
  kpi: string;
};

// === Phase-shell exports — sourced from key_numbers_python.json ===
// (Inserted by notebook cells 37b/37c/37d; consumed by Phase 2-4 screens.)

export type RiskBucketSeverity = 'H' | 'M' | 'L';

export type PhysicalBucket = {
  acute: string[];
  chronic: string[];
  covered: boolean;
  severity: RiskBucketSeverity;
};
export type DriverBucket = {
  drivers: string[];
  covered: boolean;
  severity: RiskBucketSeverity;
};
export type RiskTaxonomy = {
  physical: PhysicalBucket;
  transition: DriverBucket;
  liability: DriverBucket;
};

export const PHASE_2_TAXONOMY = canon.phase_2_taxonomy as RiskTaxonomy;

export type RiskAxis =
  | 'transition'
  | 'physical_vulnerability'
  | 'adaptive_capacity'
  | 'exposure_base';

export type IndicatorMapEntry = {
  label: string;
  risk_axis: RiskAxis;
  rationale: string;
  correlation_partial: number | null;
  correlation_pairwise: number | null;
};

export const PHASE_3_INDICATOR_MAP = canon.phase_3_indicator_map as Record<
  string,
  IndicatorMapEntry
>;

export type PanelQuality = {
  n_economies: number;
  n_years: number;
  year_min: number;
  year_max: number;
  total_cells: number;
  missing_pct_by_indicator: Record<string, number>;
  interp_method: string;
  interp_max_run: number;
  row_complete_pct: number;
};

export const PHASE_4_PANEL_QUALITY = canon.phase_4_panel_quality as PanelQuality;

export const RECOMMENDATIONS: Recommendation[] = [
  {
    id: 'parametric',
    ticker: 'PT',
    title: 'SEA Parametric Typhoon Product',
    detail:
      'Trigger: Saffir-Simpson Cat-3+ landfall in PH / VN / S-China coast. Target: top-5 primary insurers in PH and VN.',
    target: 'TAM ≈ USD 280 m premium by 2028',
    owner: 'Hannover Re APAC P&C · Product',
    milestone: 'Q3 2027 — 1st binding',
    policyId: 'sigma-1-2024',
    kpi: 'Bound GWP USD m',
  },
  {
    id: 'esg-screen',
    ticker: 'ES',
    title: 'ESG-Linked Underwriting Screen',
    detail:
      'Cedents with credible NDC-aligned transition plans receive 5–10 % premium discount. Aligned with Paris Article 2.1(c).',
    target: '+2 pp loss-ratio improvement at full adoption',
    owner: 'Hannover Re APAC · Underwriting',
    milestone: '2026 renewal cycle',
    policyId: 'paris-2-1c',
    kpi: 'LR improvement (pp)',
  },
  {
    id: 'cat-bond',
    ticker: 'CB',
    title: 'Cat Bond — 2027 Window',
    detail:
      'USD 250 m SEA multi-peril bond, timed to NGFS Disorderly Transition spread-widening window. Solvency II Art. 309 capital relief.',
    target: 'Lock spreads 12–18 months pre-repricing',
    owner: 'Hannover Re ILS · Capital Markets',
    milestone: 'Issue Q2 2027',
    policyId: 'ngfs-phaseV',
    kpi: 'Spread bps vs benchmark',
  },
  {
    id: 'capital-buffer',
    ticker: 'CL',
    title: 'Capital Loading +8 %',
    detail:
      'Hold an additional 8 % regional risk-capital buffer under Hot House scenario. Per BNM CRST 2024 §6.3.',
    target: 'Regulator-aligned',
    owner: 'Hannover Re APAC · Risk',
    milestone: 'Annual ICAAP cycle',
    policyId: 'bnm-crst-2024',
    kpi: 'Buffer held vs requirement',
  },
];
